<?xml version="1.0" encoding="UTF-8"?>
<CustomField xmlns="http://soap.sforce.com/2006/04/metadata">
    <fullName>IDM_API_Call_Failure__c</fullName>
    <defaultValue>false</defaultValue>
    <description>IDM Wrapper Code threw exception. The wrapper code that is being called either from batch job of any any adhoc call threw exception</description>
    <externalId>false</externalId>
    <inlineHelpText>Is there any exception from API Call through batch or adhoc calls?</inlineHelpText>
    <label>IDM - API Call Failure</label>
    <trackFeedHistory>false</trackFeedHistory>
    <type>Checkbox</type>
</CustomField>
